// icons 
// ASCENDING
export const ICON_ARROW_BACK = require('../assets/icons/arrow-back.png')
export const ICON_ARROW_LEFT_CIRCLE = require('../assets/icons/arrow-left-circle.png')
export const ICON_CALENDAR = require('../assets/icons/calendar.png')
export const ICON_CARD = require('../assets/icons/card.png')
export const ICON_CHECKLIST_GREEN = require('../assets/icons/checklist-green.png')
export const ICON_CHECKLIST_KEYPAD = require('../assets/icons/checklist-keypad.png')
export const ICON_CHECKLIST_WHITE = require('../assets/icons/checklist-white.png')
export const ICON_CONGRATULATIONS = require('../assets/icons/congratulations.png')
export const ICON_DOWNLOAD = require('../assets/icons/download.png')
export const ICON_GIFT = require('../assets/icons/gift.png')
export const ICON_GIFT_ACTIVE = require('../assets/icons/gift_active.png')
export const ICON_HOME = require('../assets/icons/home.png')
export const ICON_HOME_ACTIVE = require('../assets/icons/home_active.png')
export const ICON_LOGIN = require('../assets/icons/login.png')
export const ICON_LOGIN_ACTIVE = require('../assets/icons/login_active.png')
export const ICON_NOTIFICATION = require('../assets/icons/notification.png')
export const ICON_ONE_TIME_CARD = require('../assets/icons/one_time_card.png')
export const ICON_PHONEBOOK_BLUE = require('../assets/icons/phonebook-blue.png')
export const ICON_QUICK_ACCESS = require('../assets/icons/quick_access.png')
export const ICON_QUICK_ACCESS_ACTIVE = require('../assets/icons/quick_access_active.png')
export const ICON_RIGHT_ARROW_WHITE = require('../assets/icons/right-arrow-white.png')
export const ICON_SCAN = require('../assets/icons/scan.png')
export const ICON_SEARCH = require('../assets/icons/search.png')
export const ICON_SEARCH_ACTIVE = require('../assets/icons/search_active.png')
export const ICON_SHARE = require('../assets/icons/share.png')
export const ICON_STAR_OUTLINE = require('../assets/icons/star-outline.png')
export const ICON_SWIPE_BUTTON = require('../assets/icons/swipe-button.png')
export const ICON_TAP_PAY = require('../assets/icons/tap_pay.png')
export const ICON_TAP_PAY_WHITE = require('../assets/icons/tap_pay_white.png')
export const ICON_TIMER = require('../assets/icons/timer.png')

// images
export const IMAGE_AVATAR = require('../assets/images/avatar.png')
export const IMAGE_TRANSFER_SUCCESS_BG = require('../assets/images/transfer-success-bg.png')

// logos
export const LOGO_DUITNOW = require('../assets/logos/DuitNow.png')
export const LOGO_JOMPAY = require('../assets/logos/JomPay.png')
